
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ase
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: Hikari-admin
  data:
    redis:
      host: redis
      database: 10
      port: 6379
      password: macro123
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

minio:
  endpoint: http://minio:9000 #minio address
  accessKey: minioadmin #access key
  secretKey: minioadmin #access password
  volumePath: /mnt/nfs

knife4j:
  enable: false
  setting:
    language: en

unity:
  exchangeUri: https://services.api.unity.com/auth/v1/token-exchange?projectId=%s
  customIdUri: https://player-auth.services.api.unity.com/v1/projects/%s/authentication/server/custom-id
  environment: production
  saId: ea90c948-e171-4a62-aee1-78d70bbe8de9
  saSecret: HLij6ZFp3PpJLjILB4YPQvK6RRqSj5D1
  projectId: 482c3453-ab4d-44d3-b20a-6b858a2db2c2

